/*
 * Made by Wannes 'W' De Smet
 * (c) 2011 Wannes De Smet
 * All rights reserved.
 * 
 */
package net.wgr.core.access.entity;

import java.util.UUID;
import net.wgr.core.dao.AutoGenerated;
import net.wgr.core.dao.Required;

/**
 * 
 * @created Jul 24, 2011
 * @author double-u
 */
public class Rule extends net.wgr.core.dao.Object {

    // No need for UUID
    @AutoGenerated(strategy = AutoGenerated.GenerationStrategy.SEQUENTIAL)
    private long id;
    @Required
    private String path;
    private UUID target;
    private Action action = Action.DENY;

    @Override
    public String getColumnFamily() {
        return "rules";
    }

    @Override
    public String getKeyFieldName() {
        return "id";
    }

    public long getId() {
        return id;
    }

    public String getPath() {
        return path;
    }

    public UUID getTarget() {
        return target;
    }

    public Action getAction() {
        return action;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public void setTarget(UUID target) {
        this.target = target;
    }

    public void setAction(Action type) {
        this.action = type;
    }

    public enum Action {
        ALLOW, DENY
    }

    public String toString() {
        return "Rule{" + "id=" + id + ", path=" + path + ", target=" + target + ", action=" + action + '}';
    }
    
    
}
